name: qingliu
description: "清流 - 健康习惯管理工具"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  sqflite: ^2.3.3
  path: ^1.9.0
  uuid: ^4.4.2
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  fl_chart: ^0.68.0
  percent_indicator: ^4.2.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
